apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: xafrun-github
  namespace: argo
spec:
  service:
    ports:
      - port: 12000
        targetPort: 12000
  github:
    xafrun-push:
      owner: omilun
      repository: Xafrun
      webhook:
        endpoint: /xafrun/push
        port: "12000"
        method: POST
      events:
        - push
      apiToken:
        name: github-token
        key: token
      webhookSecret:
        name: github-webhook-secret
        key: secret
      insecure: false
      active: true
      contentType: json
