apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: xafrun-build
  namespace: argo
spec:
  template:
    serviceAccountName: argo-events-sa
  dependencies:
    - name: github-dep
      eventSourceName: xafrun-github
      eventName: xafrun-push
  triggers:
    - template:
        name: xafrun-workflow-trigger
        k8s:
          operation: create
          source:
            resource:
              apiVersion: argoproj.io/v1alpha1
              kind: Workflow
              metadata:
                generateName: xafrun-build-
              spec:
                workflowTemplateRef:
                  name: xafrun-build
          parameters:
            - src:
                dependencyName: github-dep
                dataKey: body.after
              dest: spec.arguments.parameters.0.value
