apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: weave-gitops
  namespace: flux-system
spec:
  interval: 1h
  chart:
    spec:
      chart: weave-gitops
      version: ">=4.0.0"
      sourceRef:
        kind: HelmRepository
        name: weave-gitops
        namespace: flux-system
  values:
    adminUser:
      create: true
      createClusterRole: true
      createSecret: true
      username: admin
      passwordHash: "$2y$10$S9Mj8SQs486x2qB.7jEiA.Ii7MPoPoq0DLtl3JUftggiYBPwDe5gm"
    rbac:
      create: true
      impersonationResourceNames: ["admin"]
      impersonationResources: ["users", "groups"]
    service:
      create: true
      type: ClusterIP
      port: 9001
