apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: fluxbaan-build
  namespace: argo
spec:
  entrypoint: pipeline
  serviceAccountName: argo-workflows-sa
  arguments:
    parameters:
      - name: commit_sha
        value: "main"

  templates:
    - name: pipeline
      dag:
        tasks:
          - name: build-backend
            template: buildkit-build
            arguments:
              parameters:
                - name: image
                  value: fluxbaan-backend
                - name: subpath
                  value: backend
                - name: sha
                  value: "{{workflow.parameters.commit_sha}}"

          - name: build-frontend
            template: buildkit-build
            arguments:
              parameters:
                - name: image
                  value: fluxbaan-frontend
                - name: subpath
                  value: frontend
                - name: sha
                  value: "{{workflow.parameters.commit_sha}}"

    - name: buildkit-build
      inputs:
        parameters:
          - name: image
          - name: subpath
          - name: sha
      container:
        image: moby/buildkit:v0.19.0
        command: [buildctl]
        args:
          - --addr=tcp://buildkitd.buildkit.svc.cluster.local:1234
          - build
          - --frontend=dockerfile.v0
          - --opt=context=https://github.com/omilun/Fluxbaan.git#{{inputs.parameters.sha}}:{{inputs.parameters.subpath}}
          - --opt=filename=Dockerfile
          - --output=type=image,name=registry.talos-tart-ha.talos-on-macos.com/{{inputs.parameters.image}}:latest,push=true
